from __future__ import annotations

import base64
import json
import mimetypes
import shutil
import subprocess
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
WEB_ROOT = PROJECT_ROOT / "web"
WEB_DIST = WEB_ROOT / "dist"
PUBLIC_DIR = PROJECT_ROOT / "public"
FRONTEND_BUNDLE = PROJECT_ROOT / "backend" / "app" / "frontend_bundle.py"


def write_python_frontend_bundle() -> None:
    index_path = PUBLIC_DIR / "index.html"
    assets: dict[str, dict[str, str]] = {}

    for file_path in sorted((PUBLIC_DIR / "assets").glob("*")):
        if not file_path.is_file():
            continue
        content_type = mimetypes.guess_type(file_path.name)[0] or "application/octet-stream"
        assets[file_path.name] = {
            "content_type": content_type,
            "body_b64": base64.b64encode(file_path.read_bytes()).decode("ascii"),
        }

    FRONTEND_BUNDLE.write_text(
        "\n".join(
            [
                "# Generated by scripts/build_web_public.py. Do not edit by hand.",
                "from __future__ import annotations",
                "",
                f"INDEX_HTML = {index_path.read_text(encoding='utf-8')!r}",
                f"ASSETS = {json.dumps(assets, ensure_ascii=False, sort_keys=True)}",
                "",
            ]
        ),
        encoding="utf-8",
    )


def main() -> None:
    subprocess.run(["npm", "run", "build"], cwd=WEB_ROOT, check=True)

    if PUBLIC_DIR.exists():
        shutil.rmtree(PUBLIC_DIR)
    PUBLIC_DIR.mkdir(parents=True, exist_ok=True)

    for item in WEB_DIST.iterdir():
        target = PUBLIC_DIR / item.name
        if item.is_dir():
            shutil.copytree(item, target)
        else:
            shutil.copy2(item, target)

    write_python_frontend_bundle()


if __name__ == "__main__":
    main()
