from __future__ import annotations

from pathlib import Path
from typing import Any

from backend.app.contracts import (
    BodySection,
    CapabilityFlags,
    HealthResponse,
    MetadataFields,
    NormalizedThesis,
    PrecheckIssue,
    PrecheckResponse,
    PrecheckSummary,
    PreviewBlock,
    ReferenceSection,
    ServiceLimits,
    SummarySection,
    TextPrecheckRequest,
)

PROJECT_ROOT = Path(__file__).resolve().parents[1]
OUTPUT_PATH = PROJECT_ROOT / "web" / "src" / "generated" / "contracts.ts"
MODELS = [
    MetadataFields,
    SummarySection,
    BodySection,
    ReferenceSection,
    CapabilityFlags,
    NormalizedThesis,
    PrecheckIssue,
    PreviewBlock,
    PrecheckSummary,
    PrecheckResponse,
    ServiceLimits,
    HealthResponse,
    TextPrecheckRequest,
]


def schema_to_ts(schema: dict[str, Any]) -> str:
    if "$ref" in schema:
        return schema["$ref"].split("/")[-1]

    if "anyOf" in schema:
        return " | ".join(schema_to_ts(item) for item in schema["anyOf"])

    schema_type = schema.get("type")
    if isinstance(schema_type, list):
        return " | ".join(ts_primitive(item) for item in schema_type)

    if schema_type == "array":
        return f"{schema_to_ts(schema['items'])}[]"
    if schema_type == "object":
        properties = schema.get("properties", {})
        lines = ["{"]
        for key, value in properties.items():
            lines.append(f"  {key}: {schema_to_ts(value)};")
        lines.append("}")
        return "\n".join(lines)
    return ts_primitive(schema_type)


def ts_primitive(schema_type: Any) -> str:
    mapping = {
        "string": "string",
        "integer": "number",
        "number": "number",
        "boolean": "boolean",
        "null": "null",
    }
    return mapping.get(schema_type, "unknown")


def render_interface(name: str, schema: dict[str, Any]) -> str:
    if schema.get("type") == "object":
        lines = [f"export interface {name} {{"]
        for key, value in schema.get("properties", {}).items():
            lines.append(f"  {key}: {schema_to_ts(value)};")
        lines.append("}")
        return "\n".join(lines)
    return f"export type {name} = {schema_to_ts(schema)};"


def main() -> None:
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)

    defs: dict[str, dict[str, Any]] = {}
    root_schemas: dict[str, dict[str, Any]] = {}
    for model in MODELS:
        schema = model.model_json_schema(ref_template="#/$defs/{model}")
        root_schemas[model.__name__] = schema
        for key, value in schema.get("$defs", {}).items():
            defs[key] = value

    seen: set[str] = set()
    chunks = [
        "// This file is generated by scripts/generate_frontend_types.py.",
        "// Do not edit manually.\n",
    ]

    for name, schema in defs.items():
        chunks.append(render_interface(name, schema))
        chunks.append("")
        seen.add(name)

    for name, schema in root_schemas.items():
        if name in seen:
            continue
        chunks.append(render_interface(name, schema))
        chunks.append("")

    OUTPUT_PATH.write_text("\n".join(chunks).rstrip() + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
